name: balloon_game
description: Hot air balloon game
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.35.0

flutter:
  uses-material-design: true
  assets:
    - assets/
